version: 2.1

jobs:
  build-extension:
      docker:
        - image: circleci/node:lts
      steps:
        - checkout
        - run:
            command: |
              npm install
  build-website:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          command: cd pAPRika
      - run: 
          command: bundle exec jekyll build --verbose
  deploy-website:
    docker:
      - image: circleci/node:lts
    steps:
      - run:
          command: cd pAPRika
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  
  ci:
    jobs:
      - build-extension
      - build-website
      - deploy-website:
          requires:
            - build-website
