version: 2.1

jobs:
  build-extension:
      docker:
        - image: circleci/node:lts
      working_directory: ~/pAPRika
      steps:
        - checkout
        - run:
            name: NPM install
            command: npm install
  build-website:
    docker:
      - image: circleci/ruby:latest
    working_directory: ~/pAPRika
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
          working_directory: ~/pAPRika/pAPRika
      - run: 
          name: Bundle Build
          command: bundle exec jekyll build --verbose
          working_directory: ~/pAPRika/pAPRika
      - run:
          name: HTMLProofer tests
          command: |
            bundle exec htmlproofer ./_site --allow-hash-href --check-html --disable-external --url-ignore "/firebase/"
          working_directory: ~/pAPRika/pAPRika
      - persist_to_workspace:
          root: ~/pAPRika/
          paths:
            - pAPRika
  deploy-website:
    docker:
      - image: circleci/node:lts
    steps:
      - run:
          command: ls
      - attach_workspace:
          at: ~/pAPRika
      - run:
          command: ls
          working_directory: ~/pAPRika/pAPRika
      - run:
          name: NPM install
          command: npm install
          working_directory: ~/pAPRika/pAPRika
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
          working_directory: ~/pAPRika/pAPRika

workflows:
  version: 2
  
  ci:
    jobs:
      - build-extension
      - build-website
      - deploy-website:
          requires:
            - build-website
