version: 2.1

jobs:
  build-extension:
      docker:
        - image: circleci/node:lts
      steps:
        - checkout
        - run:
            command: npm install
  build-website:
    docker:
      - image: circleci/ruby:latest
    working_directory: ~/pAPRika/pAPRika
    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run: 
          name: Bundle Build
          command: bundle exec jekyll build --verbose
      - run:
          name: HTMLProofer tests
          command: |
            bundle exec htmlproofer ./_site \
              --allow-hash-href \
              --check-favicon  \
              --check-html \
              --disable-external
      - persist_to_workspace:
          root: ./
          paths:
            - _site
  deploy-website:
    docker:
      - image: circleci/node:lts
    working_directory: ~/pAPRika/pAPRika
    steps:
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN

workflows:
  version: 2
  
  ci:
    jobs:
      - build-extension
      - build-website
      - deploy-website:
          requires:
            - build-website
